
name: UPenn CLO Online Community Session
pygments: true
markdown: kramdown
paginate: 10
version: 0.9

seo:
  author: Scott Schaffter, Nicholas Kingston -- Bivee
  description: UPenn CLO Online Community Group
  keywords:
  

url: 
permalink: /:year/:title
  
social:
  facebook: 
  twitter:
  linkedin:
  googleplus:
  github: 'biveeco'
  
google:
  analytics : 'UA-42533764-1'
  verification : 'SVC'

facebook:
  admins :
  api :

assets:
  img: '/assets/images/'
  css: '/assets/stylesheets/'
  js: '/assets/javascripts/'
  
